AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 20

# Exclude block length metrics for RSpec tests
Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

# Modify default Metrics/MethodLength
Metrics/MethodLength:
  Max: 15

# Disable nested module/class definitions for Rails
Style/ClassAndModuleChildren:
  Enabled: false

# Disable Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Disable include is used at the top level.
Style/MixinUsage:
  Enabled: false
