# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 865d5c29d4c3c126fb3d9504d24bb8909aba609705d75b05af0bf28872a508b717bf97df8282071da3545767e795186cb0cdf82a40c64b68a8a27fe479f31c4e

test:
  secret_key_base: 53241a5a6f347f5e9590015afea22ea34ab2180bff2996c04e8bea9f48b325518004e3b875f9db40ed17e9429f3791985878f7dc7d35c877444e69f6a1b40e82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
